import path from "path"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

process.chdir(dir)

const modelsUrl = process.env.OPENCODE_MODELS_URL || "https://models.dev"
const snapshotJs = path.join(dir, "src/provider/models-snapshot.js")
const snapshotDts = path.join(dir, "src/provider/models-snapshot.d.ts")
const minProviders = 5

const modelsData = process.env.MODELS_DEV_API_JSON
  ? await Bun.file(process.env.MODELS_DEV_API_JSON).text()
  : process.env.OPENCODE_DISABLE_MODELS_FETCH
    ? undefined
    : await fetch(`${modelsUrl}/api.json`)
        .then((x) => (x.ok ? x.text() : undefined))
        .catch(() => undefined)

async function validateSnapshot(file: string) {
  const text = await Bun.file(file).text()
  const prefix = "export const snapshot = "
  const index = text.indexOf(prefix)
  if (index < 0) throw new Error(`Invalid models snapshot format in ${file}`)
  const data = JSON.parse(text.slice(index + prefix.length).trim())
  if (!data || typeof data !== "object" || Array.isArray(data)) {
    throw new Error(`models snapshot must be a provider object`)
  }
  const count = Object.keys(data).length
  if (count < minProviders) {
    throw new Error(`models snapshot has ${count} providers; expected at least ${minProviders}`)
  }
  console.log(`Validated models snapshot (${count} providers)`)
}

if (!modelsData) {
  if (await Bun.file(snapshotJs).exists()) {
    await validateSnapshot(snapshotJs)
    console.log("Skipped models.dev fetch; using existing models-snapshot.js")
  } else {
    throw new Error(`Unable to fetch ${modelsUrl}/api.json and no local snapshot exists`)
  }
} else {
  const parsed = JSON.parse(modelsData)
  const count = Object.keys(parsed).length
  if (count < minProviders) {
    throw new Error(`models.dev api.json has ${count} providers; expected at least ${minProviders}`)
  }
  await Bun.write(
    snapshotJs,
    `// @ts-nocheck\n// Auto-generated by build.ts - do not edit\nexport const snapshot = ${modelsData}\n`,
  )
  await Bun.write(
    snapshotDts,
    `// Auto-generated by build.ts - do not edit\nexport declare const snapshot: Record<string, unknown>\n`,
  )
  await validateSnapshot(snapshotJs)
  console.log(`Generated models-snapshot.js (${count} providers)`)
}
