import path from "path"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

process.chdir(dir)

const modelsUrl = process.env.OPENCODE_MODELS_URL || "https://models.dev"
const snapshotJs = path.join(dir, "src/provider/models-snapshot.js")
const snapshotDts = path.join(dir, "src/provider/models-snapshot.d.ts")

const modelsData = process.env.MODELS_DEV_API_JSON
  ? await Bun.file(process.env.MODELS_DEV_API_JSON).text()
  : process.env.OPENCODE_DISABLE_MODELS_FETCH
    ? undefined
    : await fetch(`${modelsUrl}/api.json`)
        .then((x) => (x.ok ? x.text() : undefined))
        .catch(() => undefined)

if (!modelsData) {
  if (await Bun.file(snapshotJs).exists()) {
    console.log("Skipped models.dev fetch; using existing models-snapshot.js")
  } else {
    throw new Error(`Unable to fetch ${modelsUrl}/api.json and no local snapshot exists`)
  }
} else {
  await Bun.write(
    snapshotJs,
    `// @ts-nocheck\n// Auto-generated by build.ts - do not edit\nexport const snapshot = ${modelsData}\n`,
  )
  await Bun.write(
    snapshotDts,
    `// Auto-generated by build.ts - do not edit\nexport declare const snapshot: Record<string, unknown>\n`,
  )
  console.log("Generated models-snapshot.js")
}
